### ISSUE TITLE
Definition of Occupant Behaviour Part

### ISSUE THREAD

**Issue by aolite** [HIT2GAP-EU-PROJECT/HIT2GAPOnt#1]
Text description of the Occupant Behaviour sematic module and their corresponding parts.

**Comment by aolite** [comment]
Some text has been defined for the user behaviour part. Please review the text an the diagrams written in the following URL: https://hit2gap-eu-project.github.io/HIT2GAPOnt/

**Comment by ycardinale** [comment]
I have modified the text and proposed some modification to the class diagram.

Concerning the HIT2GAP:ParameterRange class, I agree to eliminate it, since it is redundant with “OccupantPreference”.

I also totally agree with keep separated all related to functions, services, etc that should be modeled with  OWL-S. Should we removedthe class Function related with Driver?

**Comment by aolite** [comment]
OK!!! 

I see that you have performed some changes in different branches. Can all be merged with master branch??

**Comment by aolite** [comment]
Dicussion continues on the issue #23
